# Generated by Django 2.1.7 on 2019-03-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='PIZZA NAME', max_length=30),
        ),
    ]
