# Generated by Django 2.1.7 on 2019-03-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20190308_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarow',
            old_name='name',
            new_name='content',
        ),
    ]
